# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: make73
# "service" is the name of this project. This will also be added to your AWS resource names.
service: rkconstructions

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    S3_BUCKET_NAME: rkconstructions-s3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:CreateBucket
        - s3:PutObject
        - s3:GetObject
        - s3:HeadBucket
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::rkconstructions-s3
        - arn:aws:s3:::rkconstructions-s3/*

functions:
  uploadProject:
    handler: handler.uploadProject
    events:
      - http:
          path: upload-project
          method: post
          cors: true
  getAllProjects:
    handler: getProjectHandler.getAllProjects
    events:
      - http:
          path: get-projects
          method: get
          cors: true
  getPresignedUrl:
    handler: getPresignedUrl.getPresignedUrl
    events:
      - http:
          path: get-presigned-url
          method: post
          cors: true

